# Generated by Django 4.2.7 on 2025-10-31 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_warehouse_warehouseproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsreceipt',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.warehouse'),
        ),
    ]
